spring.application.name=spring-ai-demo
spring.ai.openai.api-key=ADD_VALUE_HERE

server.port=8080

# model tuning (global defaults)
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.chat.options.max-tokens=300